version: '3.3'

services:
  web:
    build: .
    image: harbor.tandoan.asia/license_plate/api_tado:latest
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=developmen
    volumes:
      - .:/app
      - /home/tado/Desktop/TuanAn/Plate_app_TuanAn/screens:/app/screens
      - /home/tado/Desktop/TuanAn/Plate_app_TuanAn/plates:/app/plates
    restart: always

